apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hooks-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ajung/argo-dojo.git
    targetRevision: HEAD
    path: hooks-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

