apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
  labels:
    app: private-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: private-app
  labels:
    app: private-app
spec:
  selector:
    app: private-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

