apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  # Multi-Source Setup: Chart von Helm Repo + Values aus Git Repo
  sources:
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      chart: sonarqube
      targetRevision: 10.6.0+3033
      helm:
        releaseName: sonarqube
        valueFiles:
          - $values/sonarqube/values.yaml

    - repoURL: https://github.com/ajung/argo-dojo.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

