apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    demo: sync-waves
data:
  database.host: "postgres.default.svc.cluster.local"
  database.port: "5432"
  app.environment: "dojo"
  log.level: "info"

