apiVersion: v1
kind: Secret
metadata:
  name: gitlab-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  # >>> URL zu deinem privaten GitLab Repo anpassen <<<
  url: "https://gitlab.zt.msg.team/gbl/msg-technologie/cicd/argocd/sonarqube.git"
  # >>> GitLab Access Token Credentials <<<
  username: "argocd-readonly"
  password: "glpat-XXXXXXXXXXXXXXXXXXXX"
  # Nur aktivieren wenn KEIN CA-Cert in argocd-tls-certs-cm hinterlegt:
  # insecure: "true"

